### PR TITLE
Update copyright year

### PR DESCRIPTION
**Pull request by Rahmon**
Just a simple update.. :)

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by redonkulus** [comment]
Technically the copyright year does not have to be updated each year. The copyright year applies to the year the code was written. One option is to just do `2014 - Present`, then it removes the confusion.

**Comment by Rahmon** [comment]
It's a good idea.

**Comment by redonkulus** [comment]
LGTM

**Comment by redonkulus** [comment]
live now https://purecss.io/

**Pull request merged**
