### PR TITLE
Update side-menu.css

### PR DESCRIPTION
**Pull request by joseAndresGomezTovar**
To avoid the responsive side menu in MSIE is jumpy
issue #556

Please consider the following before submitting a pull request:

Guidelines for contributing: https://github.com/pure-css/pure/blob/master/CONTRIBUTING.md

Example of changes on an interactive website such as the following:

- http://jsbin.com/
- http://jsfiddle.net/
- http://codepen.io/pen/

### CODE REVIEW

**Comment by redonkulus** [comment]
@joseAndresGomezTovar does the jumpiness still occur on Edge?

**Comment by joseAndresGomezTovar** [comment]
> @joseAndresGomezTovar does the jumpiness still occur on Edge?

@redonkulus  Yes :(

**Comment by redonkulus** [comment]
Is there a fix that works for both IE and Edge? Although I don't think we should spend too much time fixing IE bugs since its a deprecates browser.

**Comment by joseAndresGomezTovar** [comment]
It just works with IE :) it's up to you if it's enough or not

**Comment by redonkulus** [comment]
I'm going to close this because I don't want to include fixes for old browsers. If you come up with a solution for Edge, then we can look into including it.

**Pull request closed without merging**
